// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Block_arrayctor_loop.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Block_arrayctor_loop::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Block_arrayctor_loop::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> Block_arrayctor_loop::ap_ST_fsm_state1 = "1";
const sc_lv<2> Block_arrayctor_loop::ap_ST_fsm_state2 = "10";
const sc_lv<32> Block_arrayctor_loop::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> Block_arrayctor_loop::ap_const_lv32_1 = "1";
const sc_lv<32> Block_arrayctor_loop::ap_const_lv32_1F = "11111";
const bool Block_arrayctor_loop::ap_const_boolean_1 = true;

Block_arrayctor_loop::Block_arrayctor_loop(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( packets_out_out_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( packets_out_out_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( col_packets_1_fu_69_p1 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( packets_out_out_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_cast_out_fu_79_p1 );

    SC_METHOD(thread_col_packets_1_fu_69_p1);
    sensitive << ( col_packets_fu_59_p4 );

    SC_METHOD(thread_col_packets_fu_59_p4);
    sensitive << ( cols_V );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( packets_out_out_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_packets_fu_73_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( col_packets_1_fu_69_p1 );

    SC_METHOD(thread_packets_fu_73_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( rows_V );

    SC_METHOD(thread_packets_out_out_blk_n);
    sensitive << ( packets_out_out_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_packets_out_out_din);
    sensitive << ( packets_out_out_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( packets_fu_73_p0 );
    sensitive << ( packets_fu_73_p1 );

    SC_METHOD(thread_packets_out_out_write);
    sensitive << ( packets_out_out_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_tmp_cast_out_fu_79_p1);
    sensitive << ( col_packets_fu_59_p4 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( packets_out_out_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "01";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Block_arrayctor_loop_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, cols_V, "(port)cols_V");
    sc_trace(mVcdFile, rows_V, "(port)rows_V");
    sc_trace(mVcdFile, packets_out_out_din, "(port)packets_out_out_din");
    sc_trace(mVcdFile, packets_out_out_full_n, "(port)packets_out_out_full_n");
    sc_trace(mVcdFile, packets_out_out_write, "(port)packets_out_out_write");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, packets_out_out_blk_n, "packets_out_out_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, col_packets_fu_59_p4, "col_packets_fu_59_p4");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, col_packets_1_fu_69_p1, "col_packets_1_fu_69_p1");
    sc_trace(mVcdFile, packets_fu_73_p0, "packets_fu_73_p0");
    sc_trace(mVcdFile, packets_fu_73_p1, "packets_fu_73_p1");
    sc_trace(mVcdFile, tmp_cast_out_fu_79_p1, "tmp_cast_out_fu_79_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

Block_arrayctor_loop::~Block_arrayctor_loop() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void Block_arrayctor_loop::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(packets_out_out_full_n.read(), ap_const_logic_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
}

void Block_arrayctor_loop::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void Block_arrayctor_loop::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void Block_arrayctor_loop::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void Block_arrayctor_loop::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(packets_out_out_full_n.read(), ap_const_logic_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void Block_arrayctor_loop::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Block_arrayctor_loop::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void Block_arrayctor_loop::thread_ap_return_0() {
    ap_return_0 = col_packets_1_fu_69_p1.read();
}

void Block_arrayctor_loop::thread_ap_return_1() {
    ap_return_1 = tmp_cast_out_fu_79_p1.read();
}

void Block_arrayctor_loop::thread_col_packets_1_fu_69_p1() {
    col_packets_1_fu_69_p1 = esl_zext<32,31>(col_packets_fu_59_p4.read());
}

void Block_arrayctor_loop::thread_col_packets_fu_59_p4() {
    col_packets_fu_59_p4 = cols_V.read().range(31, 1);
}

void Block_arrayctor_loop::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(packets_out_out_full_n.read(), ap_const_logic_1))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void Block_arrayctor_loop::thread_packets_fu_73_p0() {
    packets_fu_73_p0 =  (sc_lv<31>) (col_packets_1_fu_69_p1.read());
}

void Block_arrayctor_loop::thread_packets_fu_73_p1() {
    packets_fu_73_p1 = rows_V.read();
}

void Block_arrayctor_loop::thread_packets_out_out_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        packets_out_out_blk_n = packets_out_out_full_n.read();
    } else {
        packets_out_out_blk_n = ap_const_logic_1;
    }
}

void Block_arrayctor_loop::thread_packets_out_out_din() {
    packets_out_out_din = (!packets_fu_73_p0.read().is_01() || !packets_fu_73_p1.read().is_01())? sc_lv<32>(): sc_biguint<31>(packets_fu_73_p0.read()) * sc_bigint<32>(packets_fu_73_p1.read());
}

void Block_arrayctor_loop::thread_packets_out_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(packets_out_out_full_n.read(), ap_const_logic_1))) {
        packets_out_out_write = ap_const_logic_1;
    } else {
        packets_out_out_write = ap_const_logic_0;
    }
}

void Block_arrayctor_loop::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void Block_arrayctor_loop::thread_start_out() {
    start_out = real_start.read();
}

void Block_arrayctor_loop::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void Block_arrayctor_loop::thread_tmp_cast_out_fu_79_p1() {
    tmp_cast_out_fu_79_p1 = esl_zext<63,31>(col_packets_fu_59_p4.read());
}

void Block_arrayctor_loop::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(packets_out_out_full_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

}

